apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: david-eini12-dev
  name: enricher
spec:
  selector:
    matchLabels:
      app: enricher
  replicas: 1
  template:
    metadata:
      labels:
        app: enricher
    spec:
      containers:
        - name: enricher
          image: #########################################################
          env:
          - name: KAFKA_HOST_NAME
            valueFrom:
              secretKeyRef:
                name: enricher-secret
                key: KAFKA_HOST_NAME
          - name: KAFKA_PORT
            valueFrom:
              secretKeyRef:
                name: enricher-secret
                key: KAFKA_PORT
          - name: WEAPON_LIST_FILE_PATH
            valueFrom:
              secretKeyRef:
                name: enricher-secret
                key: WEAPON_LIST_FILE_PATH
          - name: GROUP_ID
            valueFrom:
              secretKeyRef:
                name: enricher-secret
                key: GROUP_ID
          ports:
            - containerPort: 8080
              protocol: TCP
