apiVersion: v1
kind: Secret
metadata:
  name: data-retrieval-secret
  namespace: david-eini12-dev
type: Opaque
stringData:
  MONGO_HOST: 'mongo_db'
  MONGO_PORT: '27017'
  DB_NAME: 'tweets'
  ANTISEMITE_COLLECTION_NAME: 'tweets_antisemitic'
  NOT_ANTISEMITE_COLLECTION_NAME: 'tweets_not_antisemitic'